version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./DocumentRoot:/var/www/html:z
    links:
      - 'mariadb'

  mariadb:
    image: mariadb:10.1
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'simple_user'
      MYSQL_PASSWORD: 'simple_password'
      MYSQL_DATABASE: 'simple_app'

volumes:
  mariadb: